[package]
name = "asm-demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "asm_macro"
proc-macro = true
path = "./src/asm_macro.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0"
